"""fix_diary_cascade_delete

Revision ID: 9fc495681de4
Revises: e05b8af3633f
Create Date: 2026-04-19 14:43:21.041474

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9fc495681de4'
down_revision: Union[str, Sequence[str], None] = 'e05b8af3633f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('diary_entries_product_id_fkey'), 'diary_entries', type_='foreignkey')
    op.drop_constraint(op.f('diary_entries_recipe_id_fkey'), 'diary_entries', type_='foreignkey')
    op.create_foreign_key(None, 'diary_entries', 'products', ['product_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'diary_entries', 'recipes', ['recipe_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'diary_entries', type_='foreignkey')
    op.drop_constraint(None, 'diary_entries', type_='foreignkey')
    op.create_foreign_key(op.f('diary_entries_recipe_id_fkey'), 'diary_entries', 'recipes', ['recipe_id'], ['id'])
    op.create_foreign_key(op.f('diary_entries_product_id_fkey'), 'diary_entries', 'products', ['product_id'], ['id'])
    # ### end Alembic commands ###
