"""add_cascade_to_recipe

Revision ID: e05b8af3633f
Revises: f21c54c770b7
Create Date: 2026-04-19 12:46:43.098802

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e05b8af3633f'
down_revision: Union[str, Sequence[str], None] = 'f21c54c770b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_products_name_trgm'), table_name='products', postgresql_ops={'lower(name::text)': 'gin_trgm_ops'}, postgresql_using='gin')
    op.drop_constraint(op.f('recipe_ingredients_recipe_id_fkey'), 'recipe_ingredients', type_='foreignkey')
    op.create_foreign_key(None, 'recipe_ingredients', 'recipes', ['recipe_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'recipe_ingredients', type_='foreignkey')
    op.create_foreign_key(op.f('recipe_ingredients_recipe_id_fkey'), 'recipe_ingredients', 'recipes', ['recipe_id'], ['id'])
    op.create_index(op.f('idx_products_name_trgm'), 'products', [sa.literal_column('lower(name::text)')], unique=False, postgresql_ops={'lower(name::text)': 'gin_trgm_ops'}, postgresql_using='gin')
    # ### end Alembic commands ###
